import {createServer} from 'vite';import{chromium}from'playwright';import{writeFileSync,mkdirSync}from'node:fs';
const out='../motion-benchmark-correction/depth-correction';mkdirSync(out,{recursive:true});const server=await createServer({configFile:false,optimizeDeps:{noDiscovery:true},cacheDir:`${out}/.vite`,server:{port:5193,host:'127.0.0.1',strictPort:true,hmr:false,watch:{ignored:['**']}}});await server.listen();
const browser=await chromium.launch({executablePath:'/tmp/chromium',headless:true,args:['--disable-dev-shm-usage']});const result={checks:[],errors:[],requests:[]};const check=(name,pass,detail)=>{result.checks.push({name,pass,detail});console.log(pass?'PASS':'FAIL',name,detail??'');};
try{
const page=await browser.newPage({viewport:{width:1040,height:940}});page.on('pageerror',e=>{result.errors.push(String(e));console.error(e);});page.on('console',m=>{if(m.type()==='error')console.error(m.text());});page.on('requestfailed',r=>result.requests.push({url:r.url(),error:r.failure()?.errorText}));
const open=async(reduced=false)=>{await page.goto(`http://127.0.0.1:5193/scripts/motion/depth-trace/fixture.html${reduced?'?reduced':''}`);await page.waitForSelector('[data-assets-ready=true]',{timeout:60000});};
const progress=()=>page.locator('#fixture').getAttribute('data-progress').then(Number);
const seek=async(p)=>{await page.locator('input[type=range]').evaluate((e,p)=>{e.value=p*1000;e.dispatchEvent(new Event('input',{bubbles:true}));},p);await page.waitForTimeout(80);};
await open();check('WebGL and NASA asset ready',await page.locator('canvas').getAttribute('data-ready')==='true');
await seek(.56);check('range enters crystal room',Math.abs(await progress()-.56)<.003,await page.locator('canvas').getAttribute('data-scene'));
await seek(.1);check('reverse scrubbing returns to entry',Math.abs(await progress()-.1)<.003);await seek(.79);check('monitor scene reached',await page.locator('canvas').getAttribute('data-scene')==='画面を抜ける');await seek(1);check('contact reached',await page.locator('.depth-tunnel__contact').getAttribute('aria-hidden')==='false');
await page.evaluate(()=>demo.reset());const scrollBox=await page.locator('.depth-tunnel__scroller').boundingBox();await page.mouse.move(scrollBox.x+scrollBox.width*.6,scrollBox.y+scrollBox.height*.45);await page.mouse.wheel(0,750);await page.waitForTimeout(180);check('wheel advances local scroller',await progress()>.01);check('wheel keeps outer page stable',await page.evaluate(()=>scrollY<5));
await page.locator('.depth-tunnel__scroller').focus();await page.keyboard.press('End');check('keyboard End',await progress()>.999);await page.keyboard.press('Home');check('keyboard Home',await progress()<.001);await page.keyboard.press('PageDown');check('keyboard PageDown',await progress()>.08);await page.keyboard.press('ArrowUp');check('keyboard reverse',await progress()<.11);
await page.evaluate(()=>demo.replay());await page.waitForTimeout(500);await page.locator('input[type=range]').focus();await page.keyboard.press('ArrowRight');const stopped=await progress();await page.waitForTimeout(400);check('range keyboard interrupts replay',Math.abs((await progress())-stopped)<.002);check('replay flag stopped',await page.locator('#fixture').getAttribute('data-playing')==='false');
await page.evaluate(()=>demo.replay());await page.waitForTimeout(150);await page.locator('.depth-tunnel__scroller').dispatchEvent('pointerdown');const interrupted=await progress();await page.waitForTimeout(400);check('pointer interrupts replay',Math.abs((await progress())-interrupted)<.002);
await page.evaluate(()=>demo.replay());await page.waitForTimeout(180);await page.evaluate(()=>demo.reset());await page.waitForTimeout(400);check('reset cancels and holds entrance',await progress()<.001);
const count=await page.locator('canvas').getAttribute('data-render-count');await page.waitForTimeout(400);check('no idle animation loop',count===await page.locator('canvas').getAttribute('data-render-count'));
check('no page errors',result.errors.length===0,result.errors);writeFileSync(`${out}/verification-core.json`,JSON.stringify(result,null,2));
}finally{await browser.close();await server.close();}
if(result.checks.some(c=>!c.pass)||result.errors.length)process.exitCode=1;
