export const metadata = {
  slug: "masked-lines", category: "text-reveals", title: "Masked words", subtitle: "一語ずつ、下端から持ち上がる",
  description: "Dennis Snellenberg のヒーロー直下を、白い余白・二列の紹介文・黒い円の構成ごとトレース。24個の単語を別々に切り抜き、短い時間差で下から持ち上げます。旧版の3行単位のマスクを修正しています。",
  trigger: "紹介文の画面内への進入 / スクロール / Replay",
  duration: "推定：各単語1000ms・単語間11ms（全体1253ms）",
  easing: "実測変位から近似：1 − (1 − progress)^3.6",
  timingDisclosure: "24単語×36時点の公開DOM変位を近似した値です。自由フィットは1000.3ms・10.71ms・指数3.59、変位のRMS誤差0.11px。開始直前を採取できていないため、元サイトの内部定数や厳密な発火位置とは断定していません。",
  status: "WIP",
  source: {
    name: "Dennis Snellenberg", url: "https://dennissnellenberg.com/", awardUrl: "https://www.awwwards.com/sites/dennis-snellenberg", awardDate: "2022-04-04", observedAt: "2026-10-02",
    location: "ヒーロー直下の Helping brands から始まる紹介文",
    observation: "実サイトのspan-lineは行ではなく単語の枠でした。24個の内側spanがtranslateY(100%)から0へ別々に移動。1180px幅で文字27.14px、行高39.353px、本文幅587.766px、左余白141.6pxを採寸し、途中フレームと静止画を比較しました。",
    evidence: ["2026-10-02の実サイト操作。24単語の変位を36時点採取し、途中・終了画像を目視確認。", "発火しなかった予備採取を除外し、実際に変位した採取だけで時間変化を近似。"], observationMode: "live interaction",
  },
  takeaways: ["3本の横長マスクではなく、24個の単語マスクです。同じ行でも右側の単語がわずかに遅れます。", "元サイトの白い余白、控えめな本文サイズ、左右の文章と黒い円を保ち、動きだけを切り離しません。", "出現済みの文章は表示したままにし、読み返す途中で隠しません。"],
  limitations: ["元サイト専用のDennis Sansは同梱せずArialで近似しています。字間−0.012emで字幅を補正していますが、書体による字形・行末の差は残ります。右側の紹介文は独自文です。", "元の24語と寸法・配色を観察対象として再現しています。ヒーローの写真、追従メニュー、遷移先はこの部品の対象外です。黒いAbout meの円は構図を示す非操作要素です。", "発火前の厳密なスクロール閾値は未確定です。デモは見出しの半分が画面内に入った時に一度再生。モバイルの二列解除と操作説明は学習用の追加です。"],
  usability: {
    benefit: "文章のレイアウトを変えずに、読む順序へ細かなリズムをつくります。表示後は静止します。",
    caution: "単語単位のDOMをそのまま読み上げに渡さず、文章全体を別の読み上げ用要素として残しています。",
    smallScreen: "小さい画面では二列を縦に並べ、本文サイズを確保します。Tabでスクロール領域へ移動でき、Replay・Resetはキーボードでも使えます。",
    reducedMotion: "24語を最初から表示し、フレーム更新を開始しません。設定変更時は古いインスタンスを破棄します。",
  },
  implementation: ["各単語をinline-block / overflow:hiddenで囲み、内側だけtranslateY(100%)から0へ動かします。行は可変幅で自然に折り返します。", "24語の時間差は一つのrequestAnimationFrameループで管理。有限のease-out式を実測変位に合わせ、終了後はループを止めます。", "1180pxの実測をcontainer query単位へ変換。本文27.14px、行高39.353px、左右の40pxパディングに相当する比率を保ちます。", "Resetは予約フレームを取り消して全語を隠し、Replay連打は一つの再生へ置き換えます。destroy/AbortSignalで監視・イベント・予約を解除します。"],
  xPost: "行のマスクに見えて、実際は一語ずつ。公開画面の24語を採取して、白い余白と文字サイズを含めて再構成。時間差は実測近似、専用書体は代替と明記しています。",
};
