import {createServer} from 'vite';import {chromium} from 'playwright';import {resolve} from 'node:path';import {mkdirSync,writeFileSync} from 'node:fs';import {execFileSync} from 'node:child_process';
const server=await createServer({root:process.cwd(),server:{host:'127.0.0.1',port:4209,strictPort:true}});await server.listen();const browser=await chromium.launch({headless:true,executablePath:'/tmp/chromium',args:['--disable-dev-shm-usage']});
try{for(const slug of ['gradient-frame-wipe','numeral-mask']){
 const out=resolve(`../motion-benchmark-correction/section-corrections/${slug}`),size=slug==='gradient-frame-wipe'?{width:1210,height:730}:{width:1200,height:900};mkdirSync(out,{recursive:true});
 const context=await browser.newContext({viewport:size,recordVideo:{dir:out,size},deviceScaleFactor:1});const page=await context.newPage();const video=page.video();await page.goto(`http://127.0.0.1:4209/scripts/motion/recorded-section-trace/fixture.html?slug=${slug}`);await page.waitForFunction(()=>window.ready);await page.waitForTimeout(350);await page.evaluate(()=>demo.replay());await page.waitForTimeout(slug==='gradient-frame-wipe'?4300:7350);await context.close();const file=await video.path();execFileSync('ffmpeg',['-y','-hide_banner','-loglevel','error','-i',file,'-an','-c:v','libx264','-crf','20','-pix_fmt','yuv420p',resolve(out,'replica-playback.mp4')]);
 const checks=[],errors=[],gallery=await browser.newPage({viewport:{width:1440,height:1050}});gallery.on('pageerror',error=>errors.push(error.message));const check=(name,pass)=>{checks.push({name,pass});if(!pass)process.exitCode=1;};
 await gallery.goto(`http://127.0.0.1:4209/ui-gallery/section-transitions/${slug}/`);await gallery.waitForSelector('[data-demo-ready=true]');await gallery.locator(`.${slug}__scene`).screenshot({path:resolve(out,'gallery-initial.png')});check('gallery-WIP-retained',(await gallery.locator('.motion-status').textContent()).includes('WIP'));await gallery.locator('[data-demo-replay]').click();await gallery.waitForTimeout(300);await gallery.locator('[data-demo-reset]').click();await gallery.waitForTimeout(600);check('gallery-reset-interrupts',await gallery.locator(`.${slug}`).getAttribute('data-phase')===(slug==='gradient-frame-wipe'?'outgoing':'numeral'));await gallery.locator('[data-motion-toggle]').check();await gallery.locator('[data-demo-replay]').click();check('gallery-reduced-instant',await gallery.locator(`.${slug}`).getAttribute('data-phase')==='destination');
 for(const width of [390,320]){await gallery.setViewportSize({width,height:900});await gallery.waitForTimeout(100);check(`gallery-${width}-no-overflow`,await gallery.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await gallery.locator('.motion-lab').screenshot({path:resolve(out,'gallery-mobile.png')});
 await gallery.goto(`http://127.0.0.1:4209/ui-gallery/section-transitions/`);await gallery.goBack();await gallery.waitForSelector('[data-demo-ready=true]');check('gallery-back-remount',await gallery.locator(`.${slug}`).count()===1);check('no-gallery-JS-errors',errors.length===0);writeFileSync(resolve(out,'gallery-verification.json'),JSON.stringify({checks,errors},null,2));console.log(slug,checks);await gallery.close();
}}finally{await browser.close();await server.close();}
