export const metadata = {
  slug: "icon-sequence",
  category: "buttons",
  title: "Joseph Berry / Hall of Fame",
  subtitle: "文字、四つの炎、青いカプセルの順序",
  description: "白い Hall of Fame の文字が消え、四つの炎が左から現れて消えます。その後 Let's Go の文字と青い背景へ変わる、公式映像を計測したボタンです。",
  trigger: "Hover / Replay（focus・tap はデモの代替操作）",
  duration: "約1800ms（30fps の公式映像から観測）",
  easing: "映像の不透明度・色をサンプリングし、区間を線形補間",
  timingDisclosure: "記録映像の30fpsフレームを計測した値です。原作のCSS定数や元のイージングを取得したものではありません。観測時刻は映像先頭基準で、入力イベントの正確な時刻は不明です。",
  status: "WIP",
  source: {
    name: "Joseph Berry Masterclass",
    url: "https://joseph-berry-webflow-master-class.webflow.io/",
    awardUrl: "https://www.awwwards.com/sites/joseph-berry-masterclass",
    awardDate: "2021-08-27",
    observedAt: "2026-10-02",
    observationMode: "recording-observed",
    recordingUrl: "https://www.awwwards.com/inspiration/joseph-berry-masterclass-hover-button-animation",
    location: "公式の2.467秒映像にある、黄色い背景中央の Hall of Fame ボタン",
    observation: "918×656pxの記録画面で、カプセル外周は約278×94px。最初の文字が約500msで消え、四つの炎が約200〜1000msの間に100msずつずれて現れ、同じ順番で消えます。約1100msから最後の文字が下から上がりながら現れ、約1800msで青い背景へ落ち着きます。",
    evidence: ["公式映像の全74フレームを読み、背景の色、カプセル外周、文字と炎の可視量を計測。"],
  },
  takeaways: [
    "元の白いカプセル、黄色い背景、四つの炎と文字の順序を保っています。",
    "炎は横へ移動させず、同じ位置で左から順に現れて消します。",
    "色の変化は炎が消えてから始まり、下から上がる最後の文字と重なって進みます。",
  ],
  limitations: [
    "現行サイトを操作した再現ではなく、公式の記録映像の対象部分をトレースしています。録画の画素寸法と元サイトのCSSピクセルの関係は不明です。",
    "文字はArial系の代替書体です。炎は同じUnicode絵文字ですが、Apple・Windows・Linuxなどの環境で描画が変わります。原作の絵文字画像や専用フォントはコピーしていません。",
    "色は圧縮映像から計測しているため元のCSSカラーと完全一致する保証はありません。入力からの開始時刻、元のイージング、離れた際の動きは不明です。",
    "ポインターが離れた際の即時リセット、タップとキーボードでの再生、狭い画面での寸法調整はこのデモの補助動作です。実際のページ移動は行いません。",
  ],
  usability: {
    benefit: "原作の短い順序を、同じ位置と寸法で繰り返し比較できます。演出中も再生ボタンは操作できます。",
    caution: "炎や文字が消える時間を含むため、重要な操作の名前は読み上げ側に固定しています。このデモはリンク先への移動ではなく演出の再生です。",
    smallScreen: "Tabでフォーカスし、Enter・Spaceで再生できます。タップでも同じ順序を再生し、狭い画面ではカプセルだけを収まる大きさへ調整します。",
    reducedMotion: "再生時は炎と色の途中変化を省き、青い最終状態をすぐ表示します。Resetは白い初期状態をすぐ表示します。",
  },
  implementation: [
    "記録映像から読み取った不透明度とRGB値を時間表として持ち、requestAnimationFrameで同じ時刻の状態を描きます。",
    "炎は四つのUnicode文字です。最初の炎の観測曲線を100msずつずらし、元映像の表示順序に合わせています。",
    "Reset・再生のやり直し・破棄で前の描画を停止します。意味の異なる選択状態やトグルボタンにはしていません。",
  ],
  xPost: "Hall of Fame の文字が消え、四つの炎が順番に現れ、最後に青い Let's Go へ。公式映像の寸法と途中の色・不透明度を計測して作り直しました。書体と絵文字の描画は環境による違いが残ります。",
};
