import {createServer} from 'vite';import{chromium}from'playwright';import{resolve}from'node:path';import{mkdirSync,writeFileSync}from'node:fs';
const out=resolve('../motion-benchmark-correction/image-corrections/texture-mask');mkdirSync(out,{recursive:true});
const server=await createServer({root:process.cwd(),server:{host:'127.0.0.1',port:4197,strictPort:true}});await server.listen();
const browser=await chromium.launch({headless:true,executablePath:'/tmp/chromium',args:['--disable-dev-shm-usage']});
const report={checks:[],captures:[],disclosure:'Static original-vs-replica ribbon shape samples aligned visually; source shader/input/damping unknown. Not a pixel identity claim.'};const check=(name,pass,detail)=>{report.checks.push({name,pass,detail});if(!pass)process.exitCode=1;};
try{
 const context=await browser.newContext({viewport:{width:1600,height:1300},deviceScaleFactor:1});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url='http://127.0.0.1:4197/scripts/motion/recorded-image-trace/fixture.html?slug=texture-mask';await page.goto(url);await page.waitForFunction(()=>window.ready);await page.waitForTimeout(450);
 const stage=page.locator('.texture-mask'),scene=page.locator('.texture-mask__scene'),svg=page.locator('svg');
 for(const [family,time,x,y]of[[0,1.760,570,216],[0,3.521,130,350],[1,7.042,1066,388],[1,9.682,920,280],[2,13.203,300,290],[2,14.964,910,250]]){await page.evaluate(a=>demo.sample(...a),[family,x,y]);await page.waitForTimeout(250);await scene.screenshot({path:resolve(out,`replica-${time.toFixed(3)}.png`)});report.captures.push({sourceTimestamp:time,family,pointerSample:[x,y]});}
 await page.evaluate(()=>demo.reset());check('reset-white-word',await stage.getAttribute('data-band-visible')==='false');
 await svg.focus();await page.waitForTimeout(400);check('focus-shows-material',await stage.getAttribute('data-band-visible')==='true');const before=await stage.getAttribute('data-position');await page.keyboard.press('ArrowRight');await page.waitForTimeout(600);check('keyboard-position',await stage.getAttribute('data-position')!==before);await page.keyboard.press('Escape');await page.waitForTimeout(1500);check('escape-hides-band',await stage.getAttribute('data-band-visible')==='false');
 for(let i=0;i<3;i++){await page.locator(`[data-material="${i}"]`).click();check(`family-${i}-word`,await page.locator('[data-word]').textContent()===['edstal','koveta','iflusse'][i]);check(`family-${i}-products`,await page.locator('.texture-mask__products img').first().getAttribute('src').then(s=>s.includes(['silver','black','brass'][i])));}
 await page.locator('[data-material=\"0\"]').click();await page.mouse.move(570,216);await page.waitForTimeout(600);check('pointer-shows-wide-band',await page.locator('[data-band]').evaluate(e=>e.getBBox().width>800));const p0=await stage.getAttribute('data-position');await page.mouse.move(1200,340);await page.waitForTimeout(600);check('pointer-moves-band',p0!==await stage.getAttribute('data-position'));
 await page.mouse.move(1500,1200);await page.waitForTimeout(1500);check('leave-clears-band',await stage.getAttribute('data-band-visible')==='false');
 await page.evaluate(()=>{for(let i=0;i<5;i++)demo.replay();demo.reset();});await page.waitForTimeout(700);check('repeated-replay-reset',await stage.getAttribute('data-band-visible')==='false');
 await page.evaluate(()=>demo.replay());await page.waitForTimeout(3400);check('replay-settles-hidden',await stage.getAttribute('data-band-visible')==='false');
 await page.evaluate(()=>mount(true));await page.waitForTimeout(300);check('reduced-whole-material',await page.locator('[data-material-image]').getAttribute('mask')===null);await scene.screenshot({path:resolve(out,'reduced.png')});
 await page.evaluate(()=>{mount(false);demo.replay();controller.abort();});const frozen=await stage.getAttribute('data-position');await page.waitForTimeout(400);check('abort-stops-band',frozen===await stage.getAttribute('data-position'));await page.evaluate(()=>{demo.destroy();demo.destroy();mount(false);demo.reset();});check('destroy-remount',await stage.getAttribute('data-band-visible')==='false');
 await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:780},isMobile:true,hasTouch:true,deviceScaleFactor:1});const m=await mobile.newPage();await m.goto(url);await m.waitForFunction(()=>window.ready);await m.waitForTimeout(300);await m.locator('svg').tap({position:{x:190,y:70}});await m.waitForTimeout(450);check('touch-shows-band',await m.locator('.texture-mask').getAttribute('data-band-visible')==='true');check('touch-holds-band',await m.locator('[data-hold]').getAttribute('aria-pressed')==='true');await m.locator('select').selectOption('1');check('mobile-family-selection',await m.locator('[data-word]').textContent()==='koveta');await m.locator('.texture-mask').screenshot({path:resolve(out,'mobile.png')});check('mobile-no-overflow',await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('no-page-errors',errors.length===0,errors);await mobile.close();
}finally{writeFileSync(resolve(out,'verification.json'),JSON.stringify(report,null,2));await browser.close();await server.close();}console.log(JSON.stringify(report,null,2));
