import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {listen} from '../../_motion/demo-helpers.js';
import {originalCake,originalSandwich,originalRamen} from './original-food.js';
const names=['Toast','Fish but no Head','Hotdog','Ramen Bowl','Just a Fungus','Cake Slice'];
const colors=[['#f4c522','#b51d81'],['#9dc5ca','#00458f'],['#eff319','#c94d82'],['#d91620','#b99d13'],['#cb09c8','#442596'],['#e88700','#e5ad15']];
const models={1:new URL('./assets/fish-a.glb',import.meta.url).href,2:new URL('./assets/hotdog-a.glb',import.meta.url).href,4:new URL('./assets/fungus-a.glb',import.meta.url).href};
const wrap=x=>((x%6)+6)%6;
export function createDemo(root,{signal,reducedMotion}){
 root.dataset.assetsReady='false';delete root.dataset.destroyed;delete root.dataset.assetError;
 root.innerHTML=`<section class="bending-cards"><div class="bending-cards__viewport" role="region" aria-roledescription="カルーセル" aria-label="しなる6枚の立体カード" tabindex="0"><header><span class="bending-cards__wordmark">SOFT<br>STUDY</span><p>Configurable customisable<br>extendable smooth bring<br>your own whatever slider<br>API.</p><span>EXAMPLES　DOCS　↗</span></header><canvas aria-hidden="true"></canvas><div class="bending-cards__labels" aria-hidden="true">${names.map((n,i)=>`<div><span>${String(i).padStart(4,'0')}</span><span>—</span><strong>“${n}”</strong><span>33.23¥</span></div>`).join('')}</div><div class="bending-cards__controls"><div class="bending-cards__positions">${names.map((n,i)=>`<button type="button" data-index="${i}" aria-label="${i+1}: ${n}" aria-pressed="${i===5}"><span></span></button>`).join('')}</div><div class="bending-cards__arrows"><button type="button" data-previous aria-label="前のカード">←</button><button type="button" data-next aria-label="次のカード">→</button></div></div><p class="bending-cards__fallback" hidden>3Dの表示を開始できませんでした。WebGLが使える環境で確認してください。</p></div><footer><span data-status role="status" aria-live="polite"></span><button type="button" data-pause aria-pressed="false">立体の動きを止める</button><small><a href="/ui-motion-licenses/assets/bending-cards/ATTRIBUTION.md" target="_blank" rel="noopener noreferrer">3D: QumoDone / Miroshkins / Mostafa (CC BY 4.0)</a> · ケーキ・トースト・ラーメンは独自モデル</small></footer></section>`;
 const viewport=root.querySelector('.bending-cards__viewport'),canvas=root.querySelector('canvas'),labels=[...root.querySelectorAll('.bending-cards__labels>div')],dots=[...root.querySelectorAll('[data-index]')];
 let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});}catch{root.querySelector('.bending-cards__fallback').hidden=false;root.dataset.assetsReady='true';return{reset(){},replay(){},destroy(){}};}renderer.setClearColor('#000');renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.01,100);camera.position.z=10;scene.add(new THREE.AmbientLight(0xffffff,2));const light=new THREE.DirectionalLight('#ffffff',3);light.position.set(-3,5,8);scene.add(light);
 const groups=[],panels=[],objects=[],loader=new GLTFLoader();let width=1,height=1,worldW=1,worldH=1,step=1,position=5,target=5,selected=5,velocity=0,bend=0,frame=0,last=0,time=0,dead=false,inView=true,paused=reducedMotion,pointer=null,startX=0,startY=0,startPosition=0,dragging=false,loaded=0;
 function normalize(object,i){object.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(object),size=b.getSize(new THREE.Vector3()),center=b.getCenter(new THREE.Vector3());const container=new THREE.Group();object.position.sub(center);container.add(object);const s=1/Math.max(size.x/1.25,size.y/1.45);object.scale.multiplyScalar(s);object.position.multiplyScalar(s);container.userData.baseRotation=object.rotation.clone();objects[i]=container;groups[i].add(container);loaded++;if(loaded===6)root.dataset.assetsReady='true';if(groups.length===6)render();}
 for(let i=0;i<6;i++){const group=new THREE.Group();groups.push(group);scene.add(group);const geo=new THREE.PlaneGeometry(1,1,24,30);const mat=new THREE.ShaderMaterial({uniforms:{base:{value:new THREE.Color(colors[i][0])},accent:{value:new THREE.Color(colors[i][1])},time:{value:0},shift:{value:i}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform vec3 base;uniform vec3 accent;uniform float time;uniform float shift;void main(){vec2 p=vUv-vec2(.35+.35*sin(time*.4+shift),.6+.4*cos(time*.3+shift));float f=exp(-dot(p,p)*14.);gl_FragColor=vec4(mix(base,accent,f),1.);}',side:THREE.DoubleSide});const panel=new THREE.Mesh(geo,mat);panel.userData.original=geo.attributes.position.array.slice();panels.push(panel);group.add(panel);
  if(models[i])loader.load(models[i],gltf=>{if(dead){dispose(gltf.scene);return;}gltf.scene.traverse(n=>{if(n.isMesh){const old=n.material;n.material=new THREE.MeshBasicMaterial({map:old.map,side:THREE.DoubleSide});old.dispose();}});normalize(gltf.scene,i);},undefined,()=>{loaded++;root.dataset.assetError='true';if(loaded===6)root.dataset.assetsReady='true';});
  else normalize(i===0?originalSandwich():i===3?originalRamen():originalCake(),i);
 }
 function dimensions(){width=viewport.clientWidth;height=viewport.clientHeight;camera.aspect=width/height;camera.updateProjectionMatrix();worldH=2*Math.tan(35*Math.PI/360)*10;worldW=worldH*camera.aspect;renderer.setSize(width,height,false);step=width<600?.62*worldW:.296*worldW;render();}
 function state(){selected=wrap(Math.round(target));root.dataset.position=String(selected);dots.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));root.querySelector('[data-status]').textContent=`${selected+1} / 6 · ${names[selected]}`;}
 function render(){if(dead)return;const panelW=(width<600?.47:.202)*worldW,panelH=panelW*1.375;const y=-worldH*.105;for(let i=0;i<6;i++){const distance=((i-position+3)%6+6)%6-3;groups[i].position.set(distance*step,y,0);const a=panels[i].geometry.attributes.position,base=panels[i].userData.original;for(let j=0;j<a.count;j++){const x=base[j*3],yy=base[j*3+1];a.setXYZ(j,(x+Math.cos(yy*Math.PI)*bend*.14)*panelW,yy*panelH,Math.sin(x*4+yy*.2+time*.8+i)*bend*.035*worldW);}a.needsUpdate=true;panels[i].material.uniforms.time.value=time;const object=objects[i];if(object){const scale=panelW*(1.05-Math.min(2,Math.abs(distance))*.04);object.scale.setScalar(scale);object.position.set(bend*.02*worldW,Math.sin(time*.6+i)*panelH*.025,.18);object.rotation.set(Math.sin(time*.32+i)*.12,-distance*.14+Math.sin(time*.36+i)*.32+bend*.24,Math.sin(time*.6+i)*.10+bend*.22);}
  const labelW=panelW/worldW*width,x=width/2+distance*step/worldW*width-labelW/2;labels[i].style.cssText=`left:${x}px;width:${labelW}px;top:${height/2-y/worldH*height-panelH/worldH*height/2-24}px;height:${panelH/worldH*height+48}px;`;}
 renderer.render(scene,camera);root.dataset.motionPosition=position.toFixed(4);root.dataset.bend=bend.toFixed(4);root.dataset.objectTime=time.toFixed(4);root.dataset.frame=String(Number(root.dataset.frame??0)+1);}
 function tick(now){frame=0;if(dead||!inView||document.hidden)return;const dt=Math.min(.04,(now-(last||now))/1000);last=now;const previous=position;if(!dragging){position+=(target-position)*(1-Math.exp(-8*dt));if(Math.abs(target-position)<.0001)position=target;}velocity=(position-previous)/Math.max(.016,dt);bend+=(Math.max(-1.8,Math.min(1.8,velocity*.19))-bend)*(1-Math.exp(-10*dt));if(!paused)time+=dt;render();if(!paused||Math.abs(position-target)>.0001||Math.abs(bend)>.0001||dragging)frame=requestAnimationFrame(tick);}
 function wake(){if(!frame&&!dead&&inView&&!document.hidden){last=0;frame=requestAnimationFrame(tick);}}
 function go(index){if(dead)return;target=index;state();if(reducedMotion){position=target;bend=0;render();}else wake();}
 dots.forEach((b,i)=>listen(b,'click',()=>{const base=Math.round(target);const d=((i-wrap(base)+3)%6+6)%6-3;go(base+d);},signal));listen(root.querySelector('[data-previous]'),'click',()=>go(Math.round(target)-1),signal);listen(root.querySelector('[data-next]'),'click',()=>go(Math.round(target)+1),signal);
 listen(root.querySelector('[data-pause]'),'click',e=>{paused=!paused||reducedMotion;e.currentTarget.setAttribute('aria-pressed',String(paused));e.currentTarget.textContent=paused?'立体の動きを再開':'立体の動きを止める';wake();},signal);
 listen(viewport,'keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();go(e.key==='Home'?0:e.key==='End'?5:Math.round(target)+(e.key==='ArrowRight'?1:-1));},signal);
 listen(viewport,'pointerdown',e=>{if(e.button!==0||e.target.closest('button'))return;pointer=e.pointerId;startX=e.clientX;startY=e.clientY;startPosition=position;dragging=false;},signal);
 listen(viewport,'pointermove',e=>{if(pointer!==e.pointerId)return;const dx=e.clientX-startX,dy=e.clientY-startY;if(!dragging){if(Math.abs(dy)>Math.abs(dx)&&Math.abs(dy)>8){pointer=null;return;}if(Math.abs(dx)<8)return;dragging=true;viewport.setPointerCapture(pointer);viewport.classList.add('is-dragging');}const old=position;position=startPosition-dx/(step/worldW*width);target=position;bend=reducedMotion?0:Math.max(-1.8,Math.min(1.8,(position-old)*9));state();render();wake();},signal);
 const release=e=>{if(e.type==='lostpointercapture'&&e.target!==viewport)return;if(pointer!==e.pointerId)return;const id=pointer;pointer=null;if(viewport.hasPointerCapture(id))viewport.releasePointerCapture(id);viewport.classList.remove('is-dragging');dragging=false;go(Math.round(position));};for(const name of ['pointerup','pointercancel','lostpointercapture'])listen(viewport,name,release,signal);
 const resize=new ResizeObserver(dimensions);resize.observe(viewport);const observer=new IntersectionObserver(([entry])=>{inView=entry.isIntersecting;if(inView)wake();else{cancelAnimationFrame(frame);frame=0;}},{threshold:0});observer.observe(viewport);listen(document,'visibilitychange',()=>{cancelAnimationFrame(frame);frame=0;if(!document.hidden)wake();},signal);
 function reset(){cancelAnimationFrame(frame);frame=0;if(pointer!==null&&viewport.hasPointerCapture(pointer))viewport.releasePointerCapture(pointer);pointer=null;dragging=false;viewport.classList.remove('is-dragging');position=target=5;velocity=bend=time=0;state();render();wake();}
 function dispose(object){object.traverse(n=>{n.geometry?.dispose();if(n.material){for(const m of Array.isArray(n.material)?n.material:[n.material]){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}}});}
 function destroy(){if(dead)return;dead=true;cancelAnimationFrame(frame);frame=0;if(pointer!==null&&viewport.hasPointerCapture(pointer))viewport.releasePointerCapture(pointer);pointer=null;resize.disconnect();observer.disconnect();dispose(scene);renderer.dispose();renderer.forceContextLoss();root.dataset.destroyed='true';}
 signal.addEventListener('abort',destroy,{once:true});dimensions();state();wake();return{reset,replay(){reset();go(6);},seek(p,b=0,t=0){cancelAnimationFrame(frame);frame=0;paused=true;position=target=p;bend=b;time=t;state();render();},destroy};
}
