import { createServer } from "vite";
import { chromium } from "playwright";
import AxeBuilder from "@axe-core/playwright";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const output = resolve(process.env.ORGANIC_TRACE_OUTPUT ?? "../motion-benchmark-correction/organic-audit/browser");
mkdirSync(output, { recursive: true });
const results = [], errors = [], failedResponses = [];
const check = (name, pass, detail) => { results.push({ name, pass, detail }); if (!pass) console.error("FAIL", name, detail); };
const harness = `<!doctype html><html lang="ja"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Organic trace verification</title><link rel="stylesheet" href="/ui-gallery/image-reveals/organic-mask/style.scss"><style>html,body{margin:0}.skip-link{position:absolute;transform:translateY(-200%)}*{box-sizing:border-box}</style></head><body><main id="fixture"></main><script type="module">import {createDemo} from '/ui-gallery/image-reveals/organic-mask/demo.js';window.createDemo=createDemo;window.mountOrganic=(reducedMotion=false)=>{window.organic?.destroy();window.demoSignal=new AbortController();window.organic=createDemo(document.querySelector('#fixture'),{signal:window.demoSignal.signal,reducedMotion})};window.mountOrganic();</script></body></html>`;
const server = await createServer({ server: { host: "127.0.0.1", port: 4191, strictPort: true }, plugins: [{ name: "organic-fixture", configureServer(server) { server.middlewares.use("/__organic-trace__/", async (_req, res) => { res.setHeader("Content-Type", "text/html"); res.end(await server.transformIndexHtml("/__organic-trace__/", harness)); }); } }] });
await server.listen();
const origin = "http://127.0.0.1:4191";
const browser = await chromium.launch({ headless: true, executablePath: process.env.UI_CHROMIUM_EXECUTABLE_PATH ?? "/tmp/chromium", args: ["--disable-dev-shm-usage"] });
try {
  const context = await browser.newContext({ viewport: { width: 918, height: 656 }, deviceScaleFactor: 1 });
  await context.route("**/*", route => { const url = new URL(route.request().url()); if (url.pathname.startsWith("/_vercel/")) return route.fulfill({ body: "", contentType: "application/javascript" }); return url.origin === origin ? route.continue() : route.abort(); });
  const page = await context.newPage();
  page.on("pageerror", error => errors.push(error.message));
  page.on("response", response => { if (response.status() >= 400 && response.url().startsWith(origin)) failedResponses.push({ url: response.url(), status: response.status() }); });
  await page.goto(`${origin}/__organic-trace__/`);
  await page.waitForFunction(() => document.querySelector('.organic-mask')?.dataset.loaded === 'true');
  const read = () => page.locator('.organic-mask').evaluate(s => ({ state: s.dataset.state, elapsed: s.dataset.elapsed, loaded: s.dataset.loaded, stage: s.getBoundingClientRect().toJSON(), figure: s.querySelector('figure').getBoundingClientRect().toJSON(), imageVisible: getComputedStyle(s.querySelector('img')).visibility, canvasVisible: getComputedStyle(s.querySelector('canvas')).visibility }));
  check("Initial browser load / meaningful content / no error overlay", await page.locator('button').count() === 1 && await page.locator('vite-error-overlay').count() === 0);
  await page.evaluate(async () => { await window.organic.ready; window.organic.seek(0); });
  let state = await read();
  check("Source desktop image rectangle", Math.abs(state.figure.x - 288) < .03 && Math.abs(state.figure.y - 69) < .03 && Math.abs(state.figure.width - 375) < .03 && Math.abs(state.figure.height - 534) < .03, state.figure);
  const times = [0, 66.667, 133.333, 200, 266.667, 333.333, 400, 466.667, 533.333, 600, 700, 833.333, 900];
  for (const ms of times) {
    await page.evaluate(ms => window.organic.seek(ms), ms);
    await page.screenshot({ path: resolve(output, `replica-${Math.round(ms)}.png`) });
    const raw = await page.locator('canvas').evaluate(c => c.toDataURL('image/png').split(',')[1]);
    writeFileSync(resolve(output, `canvas-${Math.round(ms)}.png`), Buffer.from(raw, 'base64'));
  }
  await page.evaluate(() => window.organic.replay());
  await page.waitForTimeout(350);
  state = await read();
  check("Playback advances through an intermediate mask", state.state === "playing" && +state.elapsed > 100 && +state.elapsed < 800, state);
  await page.waitForTimeout(800);
  state = await read();
  check("Playback settles to a complete normal image", state.state === "complete" && state.imageVisible === "visible" && state.canvasVisible === "hidden", state);
  for (const delay of [0, 60, 300, 700]) {
    await page.evaluate(() => window.organic.replay());
    await page.waitForTimeout(delay);
    await page.evaluate(() => window.organic.reset());
    await page.waitForTimeout(980);
    state = await read();
    check(`Reset cancels playback at ${delay}ms`, state.state === "ready" && +state.elapsed === 0, state);
  }
  await page.evaluate(() => { for (let i = 0; i < 15; i++) window.organic.replay(); });
  await page.waitForTimeout(1100);
  check("Repeated replay settles once", (await read()).state === "complete");
  await page.evaluate(() => window.organic.reset());
  await page.locator('button').focus(); await page.keyboard.press('Enter');
  await page.waitForTimeout(1100);
  check("Keyboard replay", (await read()).state === "complete");
  await page.evaluate(() => { window.organic.replay(); window.demoSignal.abort(); });
  const destroyed = await read(); await page.waitForTimeout(1000);
  check("Abort cancels RAF and prevents new playback", (await read()).state === "destroyed" && (await read()).elapsed === destroyed.elapsed);
  await page.evaluate(() => window.organic.replay());
  check("Destroyed replay is inert", (await read()).state === "destroyed");
  await page.evaluate(async () => { window.mountOrganic(true); await window.organic.ready; window.organic.reset(); window.organic.replay(); });
  state = await read();
  check("Reduced-motion replay/reset remain fully visible", state.state === "complete" && state.imageVisible === "visible", state);
  await page.evaluate(async () => { window.mountOrganic(false); window.organic.reset(); await window.organic.ready; });
  await page.waitForTimeout(1000);
  check("Reset during image loading is retained", (await read()).state === "ready");
  await page.evaluate(async () => { window.mountOrganic(false); window.organic.replay(); await window.organic.ready; });
  await page.waitForTimeout(1100);
  check("Replay during image loading is retained", (await read()).state === "complete");
  await page.evaluate(async () => { window.mountOrganic(false); window.demoSignal.abort(); await window.organic.ready; });
  check("Abort during loading prevents observer and paint", (await read()).state === "destroyed");
  const performance = await page.evaluate(async () => { window.mountOrganic(false); await window.organic.ready; const start = window.performance.now(); for (let i = 1; i <= 60; i++) window.organic.seek(i * 14); return (window.performance.now() - start) / 60; });
  check("Mask CPU work stays below one 60fps frame on this runner", performance < 16.7, { meanDrawMs: performance });
  for (const width of [600, 390, 320]) {
    await page.setViewportSize({ width, height: 844 });
    await page.evaluate(async () => { window.mountOrganic(false); await window.organic.ready; window.organic.seek(333.333); });
    state = await read();
    check(`${width}px mobile preserves portrait ratio and stays in bounds`, Math.abs(state.figure.width / state.figure.height - 375 / 534) < .002 && state.figure.x >= 0 && state.figure.right <= width && await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), state.figure);
    await page.screenshot({ path: resolve(output, `mobile-${width}.png`) });
  }
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${origin}/ui-gallery/image-reveals/organic-mask/`);
  await page.waitForSelector('.organic-mask[data-loaded=true]');
  await page.locator('[data-code-tab=helpers]').click();
  check("Trace notes tab exposes recorded-mask limitations", (await page.locator('[data-code-content]').textContent()).includes('14.1%') && (await page.locator('[data-code-content]').textContent()).includes('unknown original shader'));
  await page.locator('[data-code-tab=js]').click();
  await page.locator('[data-demo-replay]').click(); await page.waitForTimeout(180); await page.locator('[data-demo-reset]').click(); await page.waitForTimeout(1000);
  check("Integrated toolbar reset persists", (await read()).state === "ready");
  await page.locator('[data-motion-toggle]').check();
  await page.waitForSelector('.organic-mask[data-loaded=true]');
  check("Integrated reduced toggle", (await read()).state === "complete");
  await page.locator('.motion-lab').screenshot({ path: resolve(output, 'integrated-desktop.png') });
  const axe = await new AxeBuilder({ page }).include('.motion-lab').analyze();
  check("Integrated lab axe violations", axe.violations.length === 0, axe.violations.map(v => ({ id: v.id, impact: v.impact, count: v.nodes.length })));
  await page.goto(`${origin}/ui-gallery/image-reveals/`);
  await page.goBack(); await page.waitForSelector('.organic-mask[data-loaded=true]');
  await page.locator('[data-demo-replay]').click(); await page.waitForTimeout(1100);
  check("Back navigation restores functioning controls", (await read()).state === "complete");
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.waitForTimeout(100);
  check("OS reduced-motion change remounts safely", (await read()).state === "complete");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.motion-lab').screenshot({ path: resolve(output, 'integrated-mobile.png') });
  check("Integrated mobile has no horizontal overflow", await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  check("No runtime errors", errors.length === 0, errors);
  check("No failed local asset requests", failedResponses.length === 0, failedResponses);
  // Fail only the trace asset, leaving the photograph available.
  const fallback = await context.newPage();
  await fallback.route('**/reveal-time.png', route => route.abort());
  await fallback.goto(`${origin}/__organic-trace__/`);
  await fallback.waitForSelector('.organic-mask[data-state=fallback]');
  check("Missing mask fails open to the normal photograph", await fallback.locator('img').evaluate(img => getComputedStyle(img).visibility === 'visible'));
  await fallback.evaluate(() => { window.organic.reset(); window.organic.replay(); });
  check("Missing-mask reset/replay keep a truthful full-image status", await fallback.locator('.organic-mask').getAttribute('data-state') === 'fallback' && (await fallback.locator('[role=status]').textContent()).includes('画像全体を表示'));
  await fallback.close();
} finally { await browser.close(); await server.close(); }
writeFileSync(resolve(output, 'results.json'), JSON.stringify({ results, errors, failedResponses }, null, 2));
console.log(JSON.stringify({ passed: results.filter(r => r.pass).length, total: results.length, failures: results.filter(r => !r.pass), output }, null, 2));
if (results.some(r => !r.pass)) process.exitCode = 1;
