export const metadata = {
  slug: "vertical-aperture",
  category: "sliders",
  title: "Vertical film aperture",
  subtitle: "鋭い角と曲がる縁を残し、フィルムの境界を縦に送る",
  description: "Ciel Roseの4秒の記録から、中央の16:9の窓、縦に走る境界、往復すると膨らみ方が変わる縁をトレース。写真風の独自静止画を使った、途中状態まで比較する学習デモです。",
  trigger: "Replay / 時点スライダー / 番号・矢印・左右ドラッグ（追加操作）",
  duration: "録画トレース4s / 追加操作360ms",
  easing: "0.2s間隔の観測点を補間 / 元の曲線は不明",
  timingDisclosure: "4秒は記録全体の長さで、1枚の切り替え時間ではありません。録画の境界位置・外形を0.2秒刻みで測り、間を形状保持補間しています。手動操作の360ms応答、ドラッグ量と選択番号の閾値は学習デモ側の設計です。",
  takeaways: [
    "中央の窓はページ幅の約55%、ほぼ16:9。大きな見出しや映像上の説明を置かず、余白と小さな目盛りを保ちます。",
    "前後のシーンが同じ窓に並ぶ途中状態を、横の境界線の移動で見せます。急な逆送りも録画の時系列に沿って残します。",
    "角丸ではなく、写真の各水平行を縁の曲線に沿って伸縮。上下は直線で、四隅は鋭いままです。",
  ],
  limitations: [
    "元動画の代わりに、新しくAI生成した7枚の写真風静止画を使います。人物・構図・色・被写体内部の動きは一致しません。オリジナルの映像作品は同梱していません。",
    "4秒の公式録画だけを動きの基準にしています。元の入力がホイールかドラッグか、入力時刻や慣性、実装のイージングは確定していません。",
    "外形と境界は0.2秒間隔で採寸し、その間は補間しています。明るい全面ショットなど境界が読めない時点は目視の推定で、終端4.0sは最終フレームからの近似です。",
    "手動の番号選択・左右ドラッグ・キーボード・控えめ設定は追加した操作です。元サイトの同じ対応を検証したという意味ではありません。選択番号は最寄りのシーンで更新します。",
    "スマホでは窓を約86%幅に広げて操作しやすくしています。録画はデスクトップのみなので、元サイトのモバイル配置の再現ではありません。",
    "現在のサイトでは10作品が掲載されています。このデモは記録時の7シーンを扱い、現行版との一致は主張しません。忠実度のレビューは継続中です。",
  ],
  usability: {
    benefit: "画像が往復しても目盛りは同じ場所にあり、送り先を見失いにくくなります。時点スライダーを止めると、移動中の形も見比べられます。",
    caution: "元の入力方法が不明なためページのスクロールは奪いません。ボタンや左右ドラッグでの操作は、再生中でも今の位置から切り替えます。",
    smallScreen: "番号と前後ボタンはタップで操作できます。横ドラッグで連続移動、縦ジェスチャーはページスクロール。矢印キー・Home・Endも使えます。",
    reducedMotion: "縦移動と変形を省き、選んだ静止画へ即座に切り替えます。Replayも4秒の往復を再生せず次のシーンを表示します。",
  },
  implementation: [
    "記録のページ範囲は1600×1200内の(195,234)〜(1405,965)。各時点の上下端、左右の角、中央の曲がりを座標で保持します。",
    "Canvasの各水平行に静止画の対応行を描き、シーン境界を循環する連続位置へ変換します。border-radiusや丸いカードは使いません。",
    "順送りと逆送りの外形を別々に採寸し、逆送りで窓が縮んで縁が内側へ曲がる様子も残します。",
    "再生は1回で止まります。操作の割り込み、Reset、設定変更、非表示、ページ離脱では描画ループを止め、破棄時には画像通知・イベント・ResizeObserverも解除します。",
  ],
  xPost: "角丸ではなく、鋭い角のまま縁が曲がるフィルム窓。Ciel Roseの録画から、約55%幅の窓と上下に走る境界をトレース。画像は独自静止画に置換したWIPです。",
  status: "WIP",
  source: {
    name: "Ciel Rose",
    url: "https://cielrose.tv/",
    awardUrl: "https://www.awwwards.com/sites/ciel-rose",
    awardDate: "2025-02-20",
    observedAt: "2026-10-03",
    location: "Homepage works slider / official 4s recording",
    observation: "A centered approximately 16:9 aperture occupies about55% of the inset page. Film panels traverse it vertically with a moving horizontal seam. Sharp-corner side edges bow outward during advance and inward during reverse while the plane contracts. The fine ruler and large page margins stay in place. The footage moves internally; this implementation substitutes original generated stills.",
    observationMode: "official recording observed and measured",
    evidence: [
      "Official Awwwards MP4:1600×1200,60fps,4.000s; extracted every12frames for phase comparison.",
      "Page crop x195,y234,w1210,h731; near-rest film corners x466..1133,y392..769. Reverse sample2.6s top corners x498..1101,y423; bottomy759; center edges bow inward approximately8.5px.",
      "Seam measurements:0.0s y634;0.6s y471;1.0s y687;1.8s y496;2.4s y640;3.6s y509;3.8s y593. Coordinates are full recording pixels.",
      "Current site read-only text checked2026-10-03:ten works, so present-day count differs from the recording.",
    ],
    recordingUrl: "https://www.awwwards.com/inspiration/home-projects-slider-ciel-rose",
  },
};
