import { createServer } from 'vite';
import { chromium } from 'playwright';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const output=resolve(process.env.CHECKER_OUTPUT??'../motion-benchmark-correction/checker-correction/replica');mkdirSync(output,{recursive:true});
const results=[],errors=[],samples=[];const check=(name,pass,details)=>{results.push({name,pass,details});if(!pass)console.error(name,details);};
const origin='http://127.0.0.1:4212';
const harness=`<!doctype html><html lang="ja"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/ui-gallery/buttons/checker-dissolve/style.scss"><style>html,body{margin:0}*{box-sizing:border-box}.skip-link{display:none}#fixture .checker-dissolve{min-height:0;height:100vh}</style></head><body><main id="fixture"></main><script type="module">import{createDemo}from'/ui-gallery/buttons/checker-dissolve/demo.js';window.mount=(reducedMotion=false)=>{window.demo?.destroy();window.controller=new AbortController();window.demo=createDemo(document.querySelector('#fixture'),{signal:controller.signal,reducedMotion})};mount();</script></body></html>`;
const server=await createServer({server:{host:'127.0.0.1',port:4212,strictPort:true},plugins:[{name:'checker-fixture',configureServer(s){s.middlewares.use('/__checker/',async(req,res)=>{res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml('/__checker/',harness));});}}]});await server.listen();
const browser=await chromium.launch({headless:true,executablePath:process.env.UI_CHROMIUM_EXECUTABLE_PATH??'/tmp/chromium',args:['--disable-dev-shm-usage']});
try{
 const context=await browser.newContext({viewport:{width:400,height:240}});await context.route('**/*',r=>{const u=new URL(r.request().url());if(u.pathname.startsWith('/_vercel/'))return r.fulfill({body:''});return u.origin===origin?r.continue():r.abort()});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(origin+'/__checker/');await p.waitForFunction(()=>!!window.demo);const button=p.locator('button');
 const read=()=>p.locator('.checker-dissolve').evaluate(s=>{const b=s.querySelector('button'),m=s.querySelector('.checker-dissolve__mask'),bs=getComputedStyle(b),ms=getComputedStyle(m);return{active:s.classList.contains('is-active'),box:b.getBoundingClientRect().toJSON(),background:bs.backgroundColor,maskPosition:ms.maskPosition,maskSize:ms.maskSize,maskDuration:ms.transitionDuration,maskEasing:ms.transitionTimingFunction,baseDuration:bs.transitionDuration,baseDelay:bs.transitionDelay,maskWidth:m.getBoundingClientRect().width,maskLeft:m.getBoundingClientRect().left-b.getBoundingClientRect().left,animations:s.getAnimations({subtree:true}).filter(a=>a.playState==='running').length}});
 const rest=await read();check('Source148×43px capsule',rest.box.width===148&&rest.box.height===43,rest.box);check('Source mask rectangle and size',rest.maskWidth===158&&rest.maskLeft===-3&&rest.maskSize==='140% 100%',rest);check('Measured source transitions',rest.maskDuration==='0.6s'&&rest.maskEasing==='ease-in-out'&&rest.baseDuration==='0.3s'&&rest.baseDelay==='0.1s',rest);check('No invented selection toggle',await button.getAttribute('aria-pressed')===null);
 await p.screenshot({path:resolve(output,'rest.png')});await button.hover();await p.waitForTimeout(20);await p.evaluate(()=>{window.motionAnimations=document.querySelector('.checker-dissolve').getAnimations({subtree:true});motionAnimations.forEach(a=>a.pause())});
 for(const time of [0,100,150,200,250,300,350,400,500,600]){await p.evaluate(t=>motionAnimations.forEach(a=>a.currentTime=t),time);const state=await read();samples.push({phase:'enter',time,...state});await p.screenshot({path:resolve(output,`enter-${time}.png`)});}
 let end=await read();check('Hover reaches zero-position pale mask',end.maskPosition==='0px 0px'||end.maskPosition==='0% 0%',end);await p.evaluate(()=>motionAnimations.forEach(a=>a.finish()));await p.mouse.move(10,10);await p.waitForTimeout(20);await p.evaluate(()=>{window.motionAnimations=document.querySelector('.checker-dissolve').getAnimations({subtree:true});motionAnimations.forEach(a=>a.pause())});
 for(const time of [0,100,200,250,300,400,500,600]){await p.evaluate(t=>motionAnimations.forEach(a=>a.currentTime=t),time);samples.push({phase:'exit',time,...await read()});await p.screenshot({path:resolve(output,`exit-${time}.png`)});}
 await p.evaluate(()=>motionAnimations.forEach(a=>a.finish()));check('Exit restores original mask',(await read()).maskPosition==='350% 0px');
 for(let i=0;i<4;i++){await button.hover();await p.waitForTimeout(70);await p.mouse.move(10,10);await p.waitForTimeout(35)}await p.waitForTimeout(700);check('Rapid reversal settles at rest',!(await read()).active&&(await read()).animations===0);
 await p.evaluate(()=>demo.replay());await p.waitForTimeout(170);await p.evaluate(()=>demo.reset());await p.waitForTimeout(1400);check('Reset stops scheduled replay',(await read()).maskPosition==='350% 0px'&&!(await read()).active);
 await p.evaluate(()=>demo.replay());await p.waitForTimeout(170);await p.evaluate(()=>controller.abort());const before=await p.locator('.checker-dissolve').innerHTML();await p.waitForTimeout(1400);await p.evaluate(()=>{demo.replay();demo.reset();demo.destroy()});check('Abort prevents future mutations',before===await p.locator('.checker-dissolve').innerHTML());
 await p.evaluate(()=>mount(true));await button.focus();check('Reduced motion immediate endpoint',(await read()).animations===0&&(await read()).active);await p.evaluate(()=>demo.reset());await p.waitForTimeout(40);check('Reduced Reset returns immediately',(await read()).animations===0&&!(await read()).active);
 await p.evaluate(()=>mount());await button.focus();check('Keyboard focus reveals state',(await read()).active);await button.press('Enter');await p.waitForTimeout(80);check('Enter replays',(await read()).active);await button.press('Space');await p.waitForTimeout(80);check('Space replays',(await read()).active);
 for(const width of [390,320]){await p.setViewportSize({width,height:844});check(`${width}px no overflow`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await p.goto(origin+'/ui-gallery/buttons/checker-dissolve/');await p.waitForSelector('[data-demo-ready=true]');await p.locator('[data-motion-toggle]').check();await p.locator('[data-demo-replay]').click();check('Gallery reduced switch works',(await read()).active&&(await read()).animations===0);await p.locator('[data-demo-reset]').click();check('Gallery reset works',!(await read()).active);await p.locator('#code-helpers').click();check('Required mask asset documented',(await p.locator('[data-code-content]').textContent()).includes('checker-mask.svg'));
 const touch=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const t=await touch.newPage();await t.goto(origin+'/__checker/');await t.waitForFunction(()=>!!window.demo);check('44px touch target',(await t.locator('button').boundingBox()).height===44);await t.locator('button').tap();await t.waitForTimeout(100);check('Touch can replay',await t.locator('.checker-dissolve').evaluate(s=>s.classList.contains('is-active')));await touch.close();check('No runtime errors',errors.length===0,errors);
 writeFileSync(resolve(output,'report.json'),JSON.stringify({results,errors,scope:'Source CSS dimensions/transitions plus local behavior; source frame alignment/glyph substitution require visual review.'},null,2));writeFileSync(resolve(output,'samples.json'),JSON.stringify(samples,null,2));console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,output},null,2));if(results.some(r=>!r.pass))process.exitCode=1;
}finally{await browser.close();await server.close();}
