export const metadata = {
  slug: "magnetic-fill",
  category: "buttons",
  title: "Dennis / About me",
  subtitle: "円と文字が別々に追従する CTA",
  description: "Dennis Snellenberg の About me を部品単位で再現。白地の暗い円、下から入り上へ抜ける青、円より大きく移動する文字を、実サイトの操作・寸法と比較しています。",
  trigger: "Pointer enter / move / leave・リンク",
  duration: "Fill 約600ms / 追従・戻り 約1500ms（推定）",
  easing: "Fill: power2.inOut / 追従: power4.out / 戻り: elastic（推定）",
  status: "WIP",
  timingDisclosure: "寸法・色・レイヤー構造・strength 属性は公開画面の DOM/CSS から確認。時間と easing はライブ操作の transform 値を時系列で採取し、近似した値です。原本の JavaScript を取得したものではありません。",
  source: {
    name: "Dennis Snellenberg",
    url: "https://dennissnellenberg.com/",
    awardUrl: "https://www.awwwards.com/sites/dennis-snellenberg",
    awardDate: "2022-04-04",
    observedAt: "2026-10-02",
    location: "ホーム紹介セクションの About me。比較 viewport: 1180 × 757 CSS px",
    observation: "直径144px、暗色 #1c1d20、青 #455ce9、文字16px。青い楕円は円幅の150%・高さの200%。進入時は下から、退出時は上へ抜けます。リンク本体の strength=100、内側の文字=50。文字は円の移動に加算されます。退出時には原点を越えて揺れ戻る様子も確認しました。",
    evidence: [
      "1180×757で About me の144pxの円、65.78px幅のラベル、色、公開CSSの寸法とDOMのstrength属性を記録。",
      "同一ポインター移動を繰り返し、enter 12枚 / exit 9枚のフレームと時刻・transformを保存。600ms前後で塗りが完了、戻りは約450ms周期で減衰。",
    ],
    observationMode: "live interaction and rendered DOM/CSS measurement",
  },
  takeaways: [
    "文字の移動は円より大きい。円の strength 100 に、内側の文字の strength 50 を加えます。",
    "進入と退出は逆再生ではありません。青は下から入り、上へ抜けます。",
    "円そのものが動く原本の当たり判定を保ち、追従と弾性のある戻りを別の曲線で扱います。",
  ],
  limitations: [
    "再現範囲は About me の円形 CTA。白い部品ステージに切り出し、元ページ全体の文章、写真、スクロール連動と遷移画面は含めていません。",
    "原本の Neue Montreal は再配布せず、Arialを16px・字間補正で近似。字形は原本と異なります。",
    "600ms / 1500ms と各 easing は観測値への近似です。ツール越しの時刻には入力・描画・撮影遅延が含まれ、原本の正確な設定値とは断定しません。",
    "About me は選択トグルではなくリンクです。クリックは原本の About ページを新しいタブで開きます。別タブ化・フォーカス輪郭・タッチ押下色・動きを控える設定はギャラリー側の代替操作です。",
  ],
  usability: {
    benefit: "実際に指している位置へ円と文字が段階的に寄り、操作できる場所を知らせます。押しても Selected など別のUIには変わりません。",
    caution: "原本に合わせてリンク自体が動きます。固定した当たり判定へ作り替えてはいません。細かな操作が必要なUIへ流用する際は移動量を別途検討してください。",
    smallScreen: "540px以下・タッチでは追従を止めます。タップで参照元の About ページへ移動します。Tabのフォーカス表示と即時の青色は、観察したマウス挙動と区別した代替です。",
    reducedMotion: "位置移動と塗りの移動を止め、青・暗色の即時切り替えだけを残します。原本のマウス動作の再現とは区別しています。",
  },
  implementation: [
    "公開CSSで確認した clamp(9em, 12vw, 11em) の円と、150%×200%の楕円レイヤーを使います。1180px幅では円144px、ラベル16pxです。",
    "現在のリンクの矩形からポインター位置を正規化し、円は100、ネストした文字は50を掛けて追従させます。",
    "青は yPercent 76→0、退出は現在位置→-76。power2.inOut / 600msを採用。追従はpower4.out / 1500ms、戻りはelastic.out(1, 0.3) / 1500msで観測曲線へ近似します。",
    "Replay / Reset / ページ破棄でタイマーとGSAP tweenを解除。動きの説明、比較条件、操作補助は部品の外側に置きます。",
  ],
  xPost: "Dennis Snellenberg の About me を操作・計測して再現。青は下から入り上へ抜け、文字は円より大きく動く。似た雰囲気ではなく、静止・進入・追従・退出を比較する。時間の推定とフォントの違いも明記しています。",
};
