import { createServer } from 'vite';
import { chromium } from 'playwright';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
const output=resolve(process.env.EXO_TRACE_OUTPUT??'../motion-benchmark-correction/exo-corrections');mkdirSync(output,{recursive:true});
const cases={'directional-underline':'buttons','menu-crossfade':'image-reveals','reel-expansion':'section-transitions','underlapping-footer':'section-transitions'};
const origin='http://127.0.0.1:4196',checks=[],errors=[],samples=[];
const check=(name,pass,detail)=>{checks.push({name,pass,detail});if(!pass)console.error(name,detail);};
const near=(a,b,t=1)=>Math.abs(a-b)<=t;
const server=await createServer({server:{host:'127.0.0.1',port:4196,strictPort:true,hmr:false,watch:{ignored:['**/*']}},plugins:[{name:'exo-fixture',configureServer(s){s.middlewares.use('/__exo/',async(req,res)=>{const slug=new URL(req.url,origin).pathname.slice(1)||'menu-crossfade';if(!cases[slug]){res.statusCode=404;res.end();return;}const path=`/ui-gallery/${cases[slug]}/${slug}`;const html=`<!doctype html><html lang="ja"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="${path}/style.scss"><style>html,body{margin:0}*{box-sizing:border-box}.skip-link{display:none}</style></head><body><main id="fixture"></main><script type="module">import{createDemo}from'${path}/demo.js';window.mount=(reducedMotion=false)=>{window.demo?.destroy();window.controller=new AbortController();window.demo=createDemo(document.querySelector('#fixture'),{signal:controller.signal,reducedMotion})};mount();window.ready=true;</script></body></html>`;res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml('/__exo/'+slug,html));});}}]});await server.listen();
const browser=await chromium.launch({headless:true,executablePath:process.env.UI_CHROMIUM_EXECUTABLE_PATH??'/tmp/chromium',args:['--disable-dev-shm-usage']});
try{
 const context=await browser.newContext({viewport:{width:1180,height:830}});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
 let page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
 async function open(slug){await page.goto(`${origin}/__exo/${slug}`);await page.waitForFunction(()=>window.ready);await page.evaluate(()=>document.fonts.ready);await page.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode().catch(()=>{}))));}
 async function shot(name){console.log('capture',name);await page.screenshot({path:resolve(output,name+'.png'),timeout:10000});}
 await open('directional-underline');
 const base=await page.locator('.directional-underline').evaluate(s=>{const l=s.querySelector('.directional-underline__label'),cs=getComputedStyle(l,'::after');return{background:getComputedStyle(s).backgroundColor,font:getComputedStyle(l).fontSize,frame:s.querySelector('figure').getBoundingClientRect().toJSON(),height:cs.height,duration:cs.transitionDuration,ease:cs.transitionTimingFunction};});
 check('Menu rule, not header: 2px / .5s / source cubic',base.height==='2px'&&base.duration==='0.5s'&&base.ease==='cubic-bezier(1, 0, 0, 1)',base);check('Menu geometry source frame',near(base.frame.x,233.531)&&near(base.frame.y,200.688)&&near(base.frame.width,251.563)&&near(base.frame.height,355.625),base.frame);check('Source background and measured type size',base.background==='rgb(13, 14, 19)'&&near(parseFloat(base.font),42.6111,.1),base);
 await shot('underline-rest');await page.locator('button').nth(1).hover();await page.waitForTimeout(200);await shot('underline-enter-mid');await page.waitForTimeout(360);await shot('underline-enter-end');
 await page.mouse.move(1150,100);await page.waitForTimeout(200);await shot('underline-exit-mid');await page.waitForTimeout(360);
 check('Underline exits from right',await page.locator('.directional-underline__label').nth(1).evaluate(e=>{const s=getComputedStyle(e,'::after');return new DOMMatrix(s.transform).a===0&&parseFloat(s.transformOrigin)>0;}));
 await page.locator('button').nth(2).focus();await page.waitForTimeout(550);check('Keyboard focus exposes rule',await page.locator('button').nth(2).evaluate(e=>e.classList.contains('is-active')));await page.locator('button').nth(2).press('Enter');check('Enter gives non-navigation feedback',(await page.locator('[role=status]').innerText()).includes('News'));
 await page.evaluate(()=>{demo.replay();demo.reset()});await page.waitForTimeout(1900);check('Underline Reset clears timers',await page.locator('button.is-active').count()===0);
 await page.evaluate(()=>{demo.replay();controller.abort()});const underlineBefore=await page.locator('#fixture').innerHTML();await page.waitForTimeout(1900);await page.evaluate(()=>{demo.replay();demo.reset()});check('Underline abort freezes callbacks',underlineBefore===await page.locator('#fixture').innerHTML());
 await page.evaluate(()=>mount(true));await page.locator('button').nth(1).focus();check('Underline reduced immediate',await page.locator('.directional-underline__label').nth(1).evaluate(e=>getComputedStyle(e,'::after').transitionDuration==='0s'));
 await open('menu-crossfade');
 const menuRead=()=>page.locator('.menu-crossfade').evaluate(s=>({time:+s.dataset.traceTime,active:+s.dataset.active,frame:s.querySelector('figure').getBoundingClientRect().toJSON(),layers:[...s.querySelectorAll('[data-image]')].map(e=>{const c=getComputedStyle(e),m=new DOMMatrix(c.transform);return{o:+c.opacity,scale:Math.hypot(m.a,m.b),rotation:Math.atan2(m.b,m.a)*180/Math.PI};})}));
 await shot('menu-rest');await page.evaluate(()=>document.querySelectorAll('button')[1].dispatchEvent(new PointerEvent('pointerenter',{pointerType:'mouse'})));let elapsed=0;
 for(const t of [80,160,350,500,680,860,1020]){await page.waitForTimeout(t-elapsed);elapsed=t;const s=await menuRead();samples.push({case:'menu',nominalWaitMilestone:t,...s});await shot(`menu-${t}`);}
 const m80=samples.find(s=>s.nominalWaitMilestone===80).layers[1];check('Menu incoming scale/angle track opacity',near(m80.scale,1+.3*(1-m80.o),.001)&&near(m80.rotation,7*(1-m80.o),.001),m80);check('Menu settled endpoint',(await menuRead()).layers[1].o===1&&(await menuRead()).layers[1].rotation===0,await menuRead());
 await page.evaluate(()=>demo.replay());await page.waitForTimeout(200);await page.evaluate(()=>document.querySelectorAll('button')[3].click());await page.waitForTimeout(1100);check('Latest menu input wins after interruption',(await menuRead()).active===3&&(await menuRead()).layers[3].o===1);await page.waitForTimeout(1000);check('User input cancels preview timer',(await menuRead()).active===3);
 await page.evaluate(()=>{demo.replay();demo.reset()});await page.waitForTimeout(2500);check('Menu Reset restores first photo',(await menuRead()).active===0&&(await menuRead()).layers[0].o===1);
 await page.evaluate(()=>demo.replay());await page.waitForTimeout(200);await page.evaluate(()=>controller.abort());const menuBefore=await page.locator('#fixture').innerHTML();await page.waitForTimeout(2000);await page.evaluate(()=>{demo.replay();demo.reset()});check('Menu abort and post-destroy calls inert',menuBefore===await page.locator('#fixture').innerHTML());
 await page.evaluate(()=>mount(true));await page.locator('button').nth(2).focus();check('Reduced menu no transform/fade',(await menuRead()).layers[2].o===1&&(await menuRead()).layers[2].scale===1);
 for(const slug of ['reel-expansion','underlapping-footer']){
  await open(slug);const scroll=page.locator(`.${slug}__scroller`);await page.locator('video').evaluateAll(vs=>vs.forEach(v=>v.pause()));
  const read=()=>page.locator('.'+slug).evaluate((s,slug)=>{const scroll=s.querySelector(`.${slug}__scroller`),m=e=>new DOMMatrix(getComputedStyle(e).transform);if(slug==='reel-expansion'){const video=s.querySelector('video');return{p:+s.dataset.progress,height:scroll.clientHeight,width:scroll.clientWidth,scale:m(video).a,opacity:+getComputedStyle(video).opacity,left:m(s.querySelector('[data-left]')).e,right:m(s.querySelector('[data-right]')).e};}const back=s.querySelector(`.${slug}__backdrop`);return{p:+s.dataset.progress,height:scroll.clientHeight,width:scroll.clientWidth,footerHeight:back.clientHeight,boundary:back.getBoundingClientRect().y,content:m(s.querySelector(`.${slug}__scene`)).f,background:m(s.querySelector(`.${slug}__background`)).f};},slug);
  for(const p of slug==='reel-expansion'?[0,364.235/757,742.734/757,1]:[0,(757-439.05957)/738.40625,(757-22.70947)/738.40625,1]){
    await scroll.evaluate((e,{p,slug})=>{const d=slug==='reel-expansion'?e.querySelector(`.${slug}__runway`).clientHeight-e.clientHeight:e.querySelector(`.${slug}__backdrop`).clientHeight;e.scrollTop=p*d;e.dispatchEvent(new Event('scroll'));},{p,slug});await page.waitForTimeout(20);const s=await read();samples.push({case:slug,requestedProgress:p,...s});await shot(`${slug}-${Math.round(p*1000)}`);
    if(slug==='reel-expansion'){check(`Reel scale/text p${p.toFixed(3)}`,near(s.scale,.25+.75*p,.002)&&near(s.left,-236*(1-p),1)&&near(s.right,236*(1-p),1)&&s.opacity===.3,s);}else{const rem=(1-s.p)*s.footerHeight;check(`Footer separate ratios p${p.toFixed(3)}`,near(s.content,-rem*.5,1)&&near(s.background,-rem/2.2,1),s);}
  }
  await scroll.evaluate(e=>{e.scrollTop=e.clientHeight*.3;e.dispatchEvent(new Event('scroll'));});const reversed=await read();check(`${slug} reverse scroll returns through intermediate state`,reversed.p>0&&reversed.p<.5,reversed);
  await page.evaluate(()=>{demo.replay();demo.reset()});await page.waitForTimeout(2000);check(`${slug} Reset stops replay`,(await read()).p===0);
  await page.evaluate(()=>demo.replay());await page.waitForTimeout(450);await scroll.dispatchEvent('wheel',{deltaY:1});const interrupted=(await read()).p;await page.waitForTimeout(1700);check(`${slug} user input interrupts`,(await read()).p===interrupted);
  await page.evaluate(()=>demo.reset());await scroll.focus();await scroll.press('ArrowDown');await page.waitForTimeout(500);check(`${slug} keyboard scroll`,(await read()).p>0,await read());
  await page.evaluate(()=>demo.replay());await page.waitForTimeout(200);await page.evaluate(()=>controller.abort());const before=await read();await page.waitForTimeout(2000);await page.evaluate(()=>{demo.replay();demo.reset()});check(`${slug} abort stops all updates`,JSON.stringify(before)===JSON.stringify(await read()));
  await page.evaluate(()=>mount(true));await page.evaluate(()=>demo.replay());const reduced=await read();check(`${slug} reduced mode`,slug==='reel-expansion'?reduced.scale===1&&reduced.left===0:reduced.content===0&&reduced.background===0,reduced);if(slug==='reel-expansion')check('Reduced video paused',await page.locator('video').evaluate(v=>v.paused));
 }
 for(const slug of Object.keys(cases))for(const width of [390,320]){await page.setViewportSize({width,height:900});await open(slug);check(`${slug} ${width}px no horizontal overflow`,await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth));if(slug.includes('menu')||slug.includes('underline')){await page.locator('button').nth(2).click();await page.waitForTimeout(1100);}await shot(`${slug}-mobile-${width}`);if(slug==='reel-expansion'||slug==='underlapping-footer'){await page.locator('input[type=range]').evaluate(e=>{e.value=100;e.dispatchEvent(new Event('input'));});await page.waitForTimeout(50);await shot(`${slug}-mobile-${width}-end`);}}
 await page.close();page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));await page.setViewportSize({width:1180,height:900});
 for(const [slug,cat] of Object.entries(cases)){await page.goto(`${origin}/ui-gallery/${cat}/${slug}/`);await page.waitForSelector('[data-demo-ready=true]');check(`${slug} gallery ready`,await page.locator('h1').count()===1);await page.locator('[data-motion-toggle]').check();await page.locator('[data-demo-replay]').click();await page.locator('[data-demo-reset]').click();check(`${slug} gallery reduced toggle`,await page.locator('[data-demo-stage]').getAttribute('data-reduced-motion')==='true');}
 check('No runtime errors',errors.length===0,errors);
 writeFileSync(resolve(output,'report.json'),JSON.stringify({checks,errors,scope:'Local geometry, interaction, reduced-motion and lifecycle QA. Not an exact photographic or temporal fidelity certification; source menu trigger timestamp/ease are unknown.'},null,2));writeFileSync(resolve(output,'samples.json'),JSON.stringify(samples,null,2));console.log(JSON.stringify({passed:checks.filter(c=>c.pass).length,total:checks.length,output},null,2));if(checks.some(c=>!c.pass))process.exitCode=1;
}finally{await browser.close();await server.close();}
